[[main]]
  name = "About"
  pageRef = "about"
  weight = 1

[[main]]
  name = "Git"
  pageRef = "https://git.mcnulty.au/mcnlty/"
  weight = 2

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
